### ISSUE TITLE
pyspinw error

### ISSUE THREAD

**Issue by mincentatties** [tsdev/spinw#42]
{system: MacOS Sierra 10.12.6}

Hi Sandor

After installing pyspinw and trying your sample script I get the following:

Last login: Fri Aug 11 11:31:29 on ttys000
[rosss-imac:~] rossstewart% python3
Python 3.6.2 (default, Jul 17 2017, 16:44:45) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> spinw='/Applications/pyspinw.app/pyspinw.sh'
>>> from transplant import Matlab
>>> from transplant import MatlabStruct
>>> import numpy as np
>>> m=Matlab(spinw)
SpinW process is running...
>>> tri = m.sw_model('triAF',1.)
Preparing 'triAF' model ...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/transplant/transplant_master.py", line 124, in reader
    print(line.decode(), end='')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 41: invalid continuation byte

>>> 

Cheers
Ross

**Comment by tsdev** [comment]
This is a problem with the communication between Python and pyspinw. Can you try to rerun the same code after downloading the updated release from here:
https://github.com/tsdev/spinw/releases/tag/v3.0.2py
Please remove first the original version of pyspinw.
If the code runs, switch back on the text output by using the command in python:
`m.swpref.setpref('fid',1.)`
Then rerun the `tri = m.sw_model('triAF',1.)` command again to see if the error appears. What do you get?

**Comment by mincentatties** [comment]
That has fixed the problem.   The first time I ran
`tri = m.sw_model('triAF',1.)`
I got the same error.  Then after the `fid` setting it went away.  

Thanks

**Comment by tsdev** [comment]
I will investigate it, until then everything should still work fine, just you cannot get text output returned.

**Comment by mincentatties** [comment]
Thanks Sandor

**Comment by mincentatties** [comment]
Ok so I now get:
```
>>> m.swpref.getpref('fid')
{'label': 'file identifier for text output, default value is 1 (Command Window)', 'name': 'fid', 'val': 0.0}
```

**Comment by tsdev** [comment]
Thanks! I didn't really solved the problem, just switched of the text output in pyspinw that caused it. I will do some tests to figure out what caused it.
